export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(git zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

alias ll='ls -lah'
alias gs='git status'
alias reload!='source ~/.zshrc'
alias osint="cd ~/sovereign-osint-suite && ./main.sh"

echo "🧠 Welcome to Sovereign Terminal - AI Infrastructure Command"

[[ -f ~/.p10k.zsh ]] && source ~/.p10k.zsh